[package]
name = "homecert"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
fs = { package = "fs-err", version = "3.3.0" }
libc = "0.2.183"
rcgen = { version = "0.14.7", features = ["zeroize", "x509-parser"] }
zeroizing-alloc = "0.1.0"
